In [2]:
import numpy as np

***1D***

In [3]:
array_1d = np.array([1, 2, 3, 4 ,5])
print('1D Array:', array_1d)
print(array_1d.shape)

1D Array: [1 2 3 4 5]
(5,)


***2D***

In [3]:
array_2d = np.array([[1,2],[3,4]])
print('2D Array:', array_2d)
print(array_2d.shape)

2D Array: [[1 2]
 [3 4]]
(2, 2)


***3D***

In [6]:
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('3D Array:', array_3d)
print(array_3d.shape)

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


***Diagonal***


In [17]:
diagonally = np.diag([1,2,3,4])
print(diagonally)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Random***

In [56]:
import random

random_number = random.randint(1, 10)
print(random_number)

3


In [95]:
np.random.randint(0, 10, (2, 3))


array([[5, 3, 0],
       [1, 9, 1]])

In [59]:
M = np.random.rand(2, 2)
print(M)

[[0.49010617 0.72684662]
 [0.69576181 0.69114488]]


In [83]:
array_2d = random.randint(1, 4)
print(array_2d)

2


***Random_sample***

In [34]:
A=np.array([1,2,3,4])
print(np.random.choice(A,3))

[3 4 1]


***Element_wise operation***

In [38]:
# Addition
Add = M + array_2d
print(Add)

[[1.58169601 2.53321966]
 [3.77631765 4.58343527]]


In [36]:
# Multiplication
Multiply = array_2d * M
print(Multiply)

[[0.58169601 1.06643931]
 [2.32895296 2.33374109]]


***Max***

In [39]:
max_in_array = np.max([7,3,9,0])
print(max_in_array)

9


***Min***

In [40]:
min_in_array = np.min([7,3,9,0])
print(min_in_array)

0


***Mean***

In [41]:
mean_in_array = np.mean([7,3,9,0])
print(mean_in_array)

4.75


***Flatten***

In [44]:
Flatten = array_2d.flatten()
print(array_2d)
print(Flatten)

[[1 2]
 [3 4]]
[1 2 3 4]


***V_STACK***

In [98]:
v_stack = np.vstack((array_1d,array_1d,array_1d))
print(array_1d)
print("Vertical Stack:\n",v_stack)

[1 2 3 4 5]
Vertical Stack:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


***H_STACK***

In [100]:
h_stack = np.hstack((array_1d,array_1d))
print(array_1d)
print("Horizontal Stack:",h_stack)

[1 2 3 4 5]
Horizontal Stack: [1 2 3 4 5 1 2 3 4 5]


***Rounding_elements_in_array***

In [127]:
np.round(np.array([1.777,2.974,3.247,4.674]),)

array([2., 3., 3., 5.])

***Masked_Array***

In [109]:
masked_array = np.ma.masked_array([1, 2, 3, 4], mask=[1, 1, 0, 0])
print("Masked Array:",masked_array)

Masked Array: [-- -- 3 4]


***Advanced_indexing***

In [126]:
m_1 =np.array([[1,2],[3,4]])
m_2 = np.array([[5,6],[7,8]])
indexing = [(m_1 < 3) & (m_2 > 3)]
print(indexing)

[array([[ True,  True],
       [False, False]])]


***Creating a random permutation of an array***

In [7]:
seq = np.arange(6)
shuffled_seq = np.random.permutation(seq)
print(shuffled_seq)

[2 4 5 3 0 1]


***Concatenating two arrays***

In [24]:
arr_1 = np.arange(1,5).reshape(2,2)
arr_2 = np.arange(5,11).reshape(2,3)
print(arr_1)
print(arr_2)
print(np.concatenate((arr_1,arr_2),axis=1))

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [32]:
arr_3 = np.arange(1,7).reshape(2,3)
arr_4 = np.arange(7,13).reshape(2,3)
print(arr_3)
print(arr_4)
print(np.concatenate((arr_3,arr_4),axis=0))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


***Finding unique elements in an array***

In [34]:
arr = np.array([1,1,9,9,0,4,8])
print(np.unique(arr))

[0 1 4 8 9]


***Counting occurrences of unique elements***

In [43]:
unique,counts=np.unique(arr, return_counts=True)
print(unique,'\n',counts)

[0 1 4 8 9] 
 [1 2 1 1 2]


***Creating a mask based on a condition***

In [86]:
array = np.arange(7)
print(array)
array_masked = np.ma.masked_where(array>=5,array)
print(array_masked)


[0 1 2 3 4 5 6]
[0 1 2 3 4 -- --]


***Using np.where for multiple conditions***

In [87]:
nums = np.arange(8,16)
cond = nums[np.where ((nums>10 ) & (nums<16))]
print(nums)
print(cond)

[ 8  9 10 11 12 13 14 15]
[11 12 13 14 15]


***Saving multiple arrays to NPZ file***

In [88]:
np.savez('data_saved.npz',array,nums)

In [94]:
loaded_data = np.load('data_saved.npz')
print(loaded_data.files)
print(loaded_data ['arr_0'],loaded_data['arr_1'])

['arr_0', 'arr_1']
[0 1 2 3 4 5 6] [ 8  9 10 11 12 13 14 15]


***Creating a random seed for reproducibility***

In [112]:
np.random.seed(46)
some_matrix = np.random.rand(5,6)
print(some_matrix)

[[0.78383235 0.63483371 0.24904309 0.75807586 0.31307694 0.93723736]
 [0.04286545 0.4408672  0.91272229 0.45500392 0.50793434 0.08490795]
 [0.42634979 0.74571696 0.8670814  0.32366583 0.1040744  0.80210805]
 [0.39483195 0.62776809 0.03598854 0.29990785 0.04765322 0.37221108]
 [0.2624152  0.99052621 0.39514535 0.30753926 0.22110114 0.49402502]]


***Creating an array of a specific dtype***

In [115]:
some_array = np.arange((8),dtype= float)
print (some_array)

[0. 1. 2. 3. 4. 5. 6. 7.]


***Performing matrix multiplication***

In [157]:
mat1 = np.arange(4,16)
mat1_ = np.reshape(mat1,(4,3))
print(mat1_)

mat2 = np.arange(5,11)
mat2_ = np.reshape(mat2,(3,2))
print('\n',mat2_)

print('\n','Matrix multiplication: ','\n',np.dot(mat1_,mat2_))


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 [[ 5  6]
 [ 7  8]
 [ 9 10]]

 Matrix multiplication:  
 [[109 124]
 [172 196]
 [235 268]
 [298 340]]


***Performing element-wise comparison with tolerance***

In [159]:
comparison_with_tolerance = np.isclose(arr_2, 6, atol=1)
print(arr_2)
print("Element-wise Comparison with Tolerance 1:"'\n', comparison_with_tolerance)

[[ 5  6  7]
 [ 8  9 10]]
Element-wise Comparison with Tolerance 1:
 [[ True  True  True]
 [False False False]]


***Generating a random sample of a specified size without replacement***

In [182]:
sample = np.random.choice(np.arange(6),size=4,replace=False)
print(sample)

[4 3 2 5]


***Generating a random sample of a specified size with replacement***

In [183]:
sample_1 = np.random.choice(np.arange(6),size=4,replace=True
                           )
print(sample_1)

[1 1 2 4]


***Calculating cumulative sum of elements***

In [188]:
elements = np.arange(6).cumsum()
print(elements)

[ 0  1  3  6 10 15]


***Creating a meshgrid for 2D plotting***

In [192]:
x = np.array([3,4,5])
y = np.array([1,2])
xx ,yy = np.meshgrid(x,y)
print(xx,'\n',yy)

# (3,1) (4,1) (5,1)
# (3,2) (4,2) (5,2)


[[3 4 5]
 [3 4 5]] 
 [[1 1 1]
 [2 2 2]]


***Using np.clip to limit values in an array***

In [193]:
values = np.array([5,8,5,0,9])
clipped = np.clip(values,0,5)
print(clipped)

[5 5 5 0 5]


***Resizing an array***

In [197]:
resized = np.resize(y,(5,4))
print(resized)

[[1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]]
